x = str(input('Digite algo: ')).strip()
print(f'O tipo primitivo desse valor é {type(x)}')
print(f'Só tem espaços? {x.isspace()}')
print(f'É um número? {x.isnumeric()}')
print(f'É alfabético? {x.isalpha()}')
print(f'É alfanumérico? {x.isalnum()}')
print(f'Está em MAIÚSCULO? {x.isupper()}')
print(f'Está em MINÚSCULO? {x.islower()}')
print(f'Está capitalizada? {x.istitle()}')
